Update lesson
learn-co-curriculum/react-ts-state pull request #3
Opened 2022-09-14 21:34 UTC by jlboba

Changes made:

- Config for TS
- Added small section on typing state and updated examples accordingly. Otherwise, left this lesson mostly untouched

2022-09-22 16:54 UTC, lizbur10 requested changes

2022-09-22 16:54 UTC, lizbur10 commented on README.md
> +It may be tempting to type within the descrutctured syntax, but just as we are
Typo: descrutctured

2022-09-22 16:54 UTC, lizbur10 commented on README.md
> +the initial value. However, if it's desired to be more explicit about the type,
Is one approach preferred over the other?

2022-09-22 16:54 UTC, lizbur10 commented on README.md
> +unable to type within destructured objects, we cannot do so within destructured
Recommended rewording:

"You may recall from an earlier lesson that typing is not allowed within destructured objects; the same applies to destructured arrays as well. Typing must instead be done using the generic syntax, which will handle ..."

2022-09-22 16:54 UTC, lizbur10 commented on README.md
Missing end parenthesis on the line above

2022-09-22 16:54 UTC, lizbur10 commented on README.md
> +> Don’t call Hooks from regular TypeScript functions.
I would recommend using "JavaScript or TypeScript" here

2022-09-26 21:46 UTC, jlboba commented on README.md
> +  const [count, setCount] = useState < number > 0;
```suggestion
  const [count, setCount] = useState<number>(0);
```

2022-09-26 21:46 UTC, jlboba commented on README.md
> +  const [count, setCount] = useState < number > 0;
```suggestion
  const [count, setCount] = useState<number>(0);
```

2022-09-26 21:46 UTC, jlboba commented on README.md
> +  const [count, setCount] = useState < number > 0;
```suggestion
  const [count, setCount] = useState<number>(0);
```

2022-09-26 21:46 UTC, jlboba commented on README.md
> +    const [count, setCount] = useState < number > 0;
```suggestion
    const [count, setCount] = useState<number>(0);
```

2022-09-26 21:47 UTC, merged